## Data Loading

In [ ]:
import pandas as pd
import plotly.express as px

df= pd.read_csv("../data/student_dataset/student-mat.csv", sep=";")
print(f"{df.head(5)}, {df.shape}, {df.info()}")

<class 'pandas.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    str
 1   sex         649 non-null    str
 2   age         649 non-null    int64
 3   address     649 non-null    str
 4   famsize     649 non-null    str
 5   Pstatus     649 non-null    str
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    str
 9   Fjob        649 non-null    str
 10  reason      649 non-null    str
 11  guardian    649 non-null    str
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    str
 16  famsup      649 non-null    str
 17  paid        649 non-null    str
 18  activities  649 non-null    str
 19  nursery     649 non-null    str
 20  higher      649 non-null    str
 21  internet    649 non-null    str
 22  romantic    649 non-null    str
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), str(17)
memory usage: 200.9 KB
  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        4   0  11  11
1      5        3      3     1     1      3        2   9  11  11
2      4        3      2     2     3      3        6  12  13  12
3      3        2      2     1     1      5        0  14  14  14
4      4        3      2     1     2      5        0  11  13  13

[5 rows x 33 columns], (649, 33), None

## Inspect Missing And Duplicated Values

In [16]:
df.isna().sum()
df.duplicated().sum()

np.int64(0)

## Numerical and Categorical Columns

In [17]:
numerical_cols= df.select_dtypes(include="number").columns
print(f"Numerical Columns: {numerical_cols.tolist()}")
categorical_cols=df.select_dtypes(include=["object", "category"]).columns
print(f"Categorical Columns: {categorical_cols.tolist()}")

Numerical Columns: ['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']
Categorical Columns: ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

C:\Users\anamo\AppData\Local\Temp\ipykernel_27048\2257021374.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols=df.select_dtypes(include=["object", "category"]).columns

## Summary Statistics

In [18]:
df.describe()
df.describe(include="object")
df.describe(include="all")

C:\Users\anamo\AppData\Local\Temp\ipykernel_27048\1253408287.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649,649,649.000000,649,649,649,649.000000,649.000000,649,649,...,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
unique,2,2,NaN,2,2,2,NaN,NaN,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,GP,F,NaN,U,GT3,T,NaN,NaN,other,other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,423,383,NaN,452,457,569,NaN,NaN,258,367,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,16.744222,NaN,NaN,NaN,2.514638,2.306626,NaN,NaN,...,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,NaN,NaN,1.218138,NaN,NaN,NaN,1.134552,1.099931,NaN,NaN,...,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,NaN,NaN,15.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,16.000000,NaN,NaN,NaN,2.000000,1.000000,NaN,NaN,...,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,NaN,NaN,17.000000,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN,...,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,NaN,NaN,18.000000,NaN,NaN,NaN,4.000000,3.000000,NaN,NaN,...,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,NaN,NaN,22.000000,NaN,NaN,NaN,4.000000,4.000000,NaN,NaN,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

## Explore the sidtribution of final grades

In [19]:
fig = px.histogram(
    df,
    x="G3",
    title="Distribution of Final Grades",
    labels={
        "G3": "Final Grade",
        "count": "Number of Students"
    }
)
fig.show()

## Study time against final grade

In [21]:
fig = px.box(
    df,
    x="studytime",
    title="Study time vs Final Grade",
    labels={
        "studytime":"Weekly study time category",
        "G3": "Final Grade",
    }
)
fig.show()

## Absence and final grades

In [26]:
fig = px.histogram(
    df,
    x="absences",
    title="Distribution of Student Absence",
    labels={
        "absences": "Number of Absence",
        "count": "Number of Students"
    }
)
fig.show()
fig = px.scatter(
    df,
    x="absences",
    title="Student Absences Vs Final Grades",
    labels={
        "absences": "Number of Absences",
        "G3": "Final Grade",
    }
)
fig.show()
df[["absences", "G3"]].corr()

          absences        G3
absences  1.000000 -0.091379
G3       -0.091379  1.000000

## Previous Failures and grades

In [28]:
fig = px.box(
    df,
    x="failures",
    title="Previous Failures vs Final Grades",
    labels={
        "failures": "Number of Previous Failures",
        "G3": "Final Grade"
        }
)
fig.show()

## Relationship between G1, G2, G3

In [29]:
grade_corr=df[["G1", "G2", "G3"]].corr()
fig=px.imshow(
    grade_corr,
    title="Correlation between period grades"
)
fig.show()